# Generated by Django 5.2.7 on 2025-10-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.TextField(blank=True, choices=[('Advogado', 'Advogado'), ('Analista', 'Analista'), ('Gerente executivo', 'Gerente executivo'), ('Assistente adm', 'Assistente adm'), ('Estagiário', 'Estagiário'), ('Fiscal', 'Fiscal'), ('Jovem aprendiz', 'Jovem aprendiz'), ('Supervisor', 'Supervisor'), ('Auditor', 'Auditor'), ('Coordenador', 'Coordenador'), ('Operador', 'Operador'), ('Executivo de vendas', 'Executivo de vendas'), ('Gerente', 'Gerente'), ('Diretor', 'Diretor'), ('Auxiliar', 'Auxiliar')], default='Analista', null=True),
        ),
    ]
