# Generated by Django 5.2.7 on 2025-10-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='setor',
            field=models.TextField(blank=True, choices=[('Marketing', 'Marketing'), ('Comercial', 'Comercial'), ('Auditoria', 'Auditoria'), ('Recursos Humanos', 'Recursos Humanos'), ('TI', 'TI'), ('TD', 'TD'), ('Contabilidade', 'Contabilidade'), ('Outros', 'Outros')], default='Outros', null=True),
        ),
    ]
