"""
Django settings for settings project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url as db_url

load_dotenv()

# *Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# !SECURITY WARNING: keep the secret key used in production secret!
env_path = os.path.join(BASE_DIR, '.secrets/.env')
load_dotenv(dotenv_path=env_path)

SECRET_KEY = os.getenv('SECRET_KEY')

# !SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS - Aceita variável de ambiente E adiciona padrões
ALLOWED_HOSTS = []

# Adiciona hosts da variável de ambiente (se existir)
allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '')
if allowed_hosts_env:
    ALLOWED_HOSTS.extend([h.strip() for h in allowed_hosts_env.split(',') if h.strip()])

# SEMPRE adiciona hosts padrões (mesmo que venha da env)
ALLOWED_HOSTS.extend([
    'localhost',
    '127.0.0.1',
    '.ngrok-free.app',
    '.ngrok.io',
    '.ngrok.app',
    '.trycloudflare.com',
    '.onrender.com',
    'mapa-do-bosque-2.onrender.com',  # Domínio específico do Render
])

# Remove duplicatas mantendo ordem
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))

# *CSRF trusted origins for ngrok e cloudflare
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',  # Frontend local
    'http://localhost:8000',  # Backend local
    'http://127.0.0.1:5173',  # Frontend local
    'http://127.0.0.1:8000',  # Backend local
    'https://*.ngrok-free.app',
    'https://*.ngrok.io',
    'https://*.ngrok.app',
    'https://*.trycloudflare.com',  # Cloudflare Tunnel
    'https://*.onrender.com',  # Render.com (wildcard)
    'https://mapa-do-bosque-2.onrender.com',  # Domínio específico
]


# *Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',  # Para criar tokens de autenticação
    'api',  # App principal com autenticação e API
    'wbr',  # WBR Analytics - API para gráficos
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve arquivos estáticos em produção
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS Configuration
# Nota: Quando frontend e backend estão na mesma origem (deploy unificado),
# CORS não é necessário. Mas mantemos para desenvolvimento local separado.
CORS_ALLOW_ALL_ORIGINS = True  # Simplificado para desenvolvimento

# Configurações adicionais de CORS
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

ROOT_URLCONF = 'mapaconfig.urls'

# Caminho para o build do React (frontend/dist)
FRONTEND_DIR = os.path.join(BASE_DIR.parent, 'frontend', 'dist')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [FRONTEND_DIR] if os.path.exists(FRONTEND_DIR) else [],  # Adiciona o build do React para servir o index.html
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mapaconfig.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASE_URL = os.getenv('DATABASE_URL')

DATABASES = {
    'default': {
        **db_url.parse(DATABASE_URL),
        'CONN_MAX_AGE': 0,  # Fecha conexões após cada request
        'OPTIONS': {
            'connect_timeout': 10,
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Fortaleza'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Diretórios adicionais onde o Django procura arquivos estáticos
# Inclui os assets do build do React (JS, CSS, imagens)
STATICFILES_DIRS = [
    os.path.join(FRONTEND_DIR, 'assets'),  # Vite coloca JS/CSS compilados em dist/assets
] if os.path.exists(FRONTEND_DIR) else []

# WhiteNoise configuration for serving static files in production
# Usando CompressedStaticFilesStorage ao invés de CompressedManifestStaticFilesStorage
# O Manifest é muito rigoroso e causa erro 500 se houver problemas com referências
# O CompressedStaticFilesStorage comprime arquivos mas é mais tolerante
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# WhiteNoise - Allow serving index.html with immutable cache
WHITENOISE_AUTOREFRESH = DEBUG  # Auto-refresh em dev, cache em produção
WHITENOISE_USE_FINDERS = DEBUG  # Usa staticfiles finders em dev
WHITENOISE_ALLOW_ALL_ORIGINS = True  # Permite CORS para assets

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Removido LOGIN_URL pois usamos API REST, não formulários HTML

# User Model customizado
AUTH_USER_MODEL = 'api.User'

# Configuração do Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # Autenticação por Token
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Por padrão, todas as rotas precisam de autenticação
    ],
}

# Configuração de Email (Outlook)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')


# ==========================
# WBR ANALYTICS SETTINGS
# ==========================

# Connection String para WBR (reutiliza DATABASE_URL)
DATABASES['default']['CONN_STRING'] = DATABASE_URL

# WBR Configuration
WBR_DB_POOL_SIZE = int(os.getenv('WBR_DB_POOL_SIZE', '20'))  # 20 conexões para queries paralelas
WBR_QUERY_TIMEOUT = int(os.getenv('WBR_QUERY_TIMEOUT', '30'))  # 30 segundos timeout
WBR_CACHE_ENABLED = os.getenv('WBR_CACHE_ENABLED', 'False').lower() == 'true'
WBR_REDIS_URL = os.getenv('WBR_REDIS_URL', None)  # Ex: redis://localhost:6379/0
WBR_CACHE_TTL = int(os.getenv('WBR_CACHE_TTL', '3600'))  # 1 hora (3600 segundos)
WBR_LOG_LEVEL = os.getenv('WBR_LOG_LEVEL', 'INFO')  # DEBUG, INFO, WARNING, ERROR, CRITICAL
WBR_LOG_FORMAT = os.getenv('WBR_LOG_FORMAT', 'json')  # json ou text

# ==========================
# LOGGING CONFIGURATION
# ==========================
# Adicionar logging para DEBUG=False para capturar erros
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
